In [46]:
import numpy as np

graph = np.zeros([800, 800], dtype='int')

In [47]:
select_specials = np.unique(np.random.randint(0, 800, size=50))
select_specials

array([  6,  14,  24,  36,  39,  68, 113, 114, 117, 141, 172, 189, 223,
       266, 292, 332, 374, 385, 414, 420, 437, 443, 451, 465, 475, 481,
       493, 508, 516, 518, 527, 533, 537, 563, 573, 609, 649, 669, 677,
       680, 686, 696, 699, 702, 739, 753])

In [48]:
for ni in select_specials:
    connect_to = np.unique(np.random.randint(0, 800, size=np.random.randint(300, 500)))
    graph[ni, connect_to] = 1
    graph[connect_to, ni] = 1
    
    

In [56]:
with open('graph.txt', 'w') as f:
    for i in range(800):
        for j in range(i+1, 800):
            if graph[i, j] == 1:
                f.write(str(i) + ' ' + str(j) + '\n')
    
    f.close()
print('done')

done


In [67]:
gr = np.array([
    [1, 2, 3, 4, 5],
    [2, 2, 3, 4, 5],
    [3, 2, 3, 4, 1],
    [4, 1, 1, 1, 1],
    [5, 2, 3, 4, 1]
])
x = np.array([
    1, 0, 1, 1, 0
])
m1 = np.multiply(x, gr)
print(m1)
nx = 1 - x
m2 = np.multiply(nx.reshape(-1, 1), m1)
print(m2)

[[1 0 3 4 0]
 [2 0 3 4 0]
 [3 0 3 4 0]
 [4 0 1 1 0]
 [5 0 3 4 0]]
[[0 0 0 0 0]
 [2 0 3 4 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [5 0 3 4 0]]
